#!/bin/bash
# Для правильной подсветки редакторами. Это shell library

# Не запускать в контексте неотключаемого set +e
where(){
	(
		set -e

		[ $# != 1 ] && echo "Usage: where COMMAND" >&2 && return 1

		COMMAND="$1"

		case "$(type -t "$COMMAND" || :)" in
			alias)
				# Этот вариант работает только в простых случаях

				type "$COMMAND"

				ALIAS_RETURNED="$(alias "$COMMAND")"

				unalias "$COMMAND"

				COMMAND="${ALIAS_RETURNED#"alias $COMMAND='"}"
				COMMAND="${COMMAND%\'}"

				read -r COMMAND ETC <<< "$COMMAND"

				if ! printf '%s\n' "$COMMAND" | grep '[]0-9a-zA-Z_.:-]' > /dev/null; then
					echo "Too difficult"
					return
				fi

				where "$COMMAND"
				;;

			keyword|builtin)
				type "$COMMAND"
				echo "Try \"help $COMMAND\""
				;;

			function)
				type "$COMMAND" | head -n 1
				;;

			file)
				type "$COMMAND"
				printf 'Symlink chain: '
				as-readlink "$(type -p "$COMMAND")"
				if DPKG="$(dpkg -S "$(readlink -f "$(type -p "$COMMAND")")")"; then
					printf '%s\n' "Debian package: ${DPKG%:*}"
					echo "For tpm: prog:$COMMAND:${DPKG%:*}"
					echo "Try \"$COMMAND --help\", \"man 1 $COMMAND\", \"man 6 $COMMAND\", \"man 8 $COMMAND\", \"aptitude show ${DPKG%:*}\""
				else
					dpkg -S "$(readlink -f "$(type -p "$COMMAND")")" || :
					echo "Try \"$COMMAND --help\""
				fi
				;;

			"")
				type "$COMMAND"
				;;
		esac
	)
}
